### PR TITLE
Add gesture detectors with callbacks for when tapping cells.

### PR DESCRIPTION
**Pull request by recycledhumanoid**
They can be used by setting these properties:

onStickyLegendPressed: () => print('Sticky legend pressed.'),
onColumnTitlePressed: (i) => print('Column $i title pressed.'),
onRowTitlePressed: (j) => print('Row $j title pressed.'),
onContentCellPressed: (i, j) => print('Cell at column $i, row $j pressed.'),

### CODE REVIEW

**Comment by AlexBacich** [comment]
@recycledhominid , thanks for your interest in library. 

There is another way for doing gesture recoginzers: simply build cells with Gesture Detectors. Here's example: https://github.com/AlexBacich/sticky-headers-table/blob/master/example/lib/tap_handler_page.dart

Do you think it is worth adding another parameters in constructor instead?

**Comment by recycledhominid** [comment]
I thought about wrapping the cells with Gesture Detectors, but this results in only the cell contents being tappable, when I want to whole cell area to be tappable.

image

In the above example you can see the Flat Buttons with red, aligned to the right using the cellAlignments property, which leaves all this empty space to the left in blue which is untappable and might be a bad UX if the user tries to tap the cell in that area.

That's why I wrapped the whole cell Container with a GestureDetector inside StickyHeadersTable.

I thought it's a useful feature to have, hence the PR, but I understand if you don't want to merge, I can just keep it in my fork.

**Comment by AlexBacich** [comment]
OK, that makes sense. Anyway, having dedicated gesture detectors makes it more clear to use. 

For initial ScrollOffsetProperties - that makes sense. 
As for onEndScrolling callback - I didn't quite understand its purpose. I can have this callback, but what is practical usage? I've tried to setup as you described in readme.md but didn't see any difference. 

Lastly - examples are throwing errors now if initialScrollOffset properties or onEndScrolling callback are ommitted. Since these are optional parameters - sticky headers should handle this. For example, provide default values. Right now examples start failing with your code. 

One last note - this seems wrong to me: () => null. Better to put null instead. 

And one last-last note. As you researched the library - do you have an idea how to solve this issue? 
https://github.com/AlexBacich/sticky-headers-table/issues/19

**Comment by recycledhominid** [comment]
Oh sorry I didn't realise my last two commits went into the PR! I'll fix the problems now.

My goal for the initial scroll offsets and onEndScrolling was to be able to stay at the current scroll position after a rebuild (ex. fetching new data from the database and rebuilding the table). The initial scroll offset is obvious. The purpose of onEndScrolling is to get the latest scroll offsets from the table widget and store them in the parent widget, assuming the parent widget keeps its state.

So let's say you scroll to (x, y) position, onEndScrolling will get called and you store these values in the parent widget. Then after a rebuild, you provide these values as initial scroll offsets so you return to the same position.

**Comment by recycledhominid** [comment]
As for #19, no clue, but to be honest it doesn't really bother me, at least not enough to spend time to fix it!

If it was during regular scrolling then it would be a problem, but it only happens when you hold the position in overscroll and it's not like the user will try to read the table when holding the overscroll.

**Comment by AlexBacich** [comment]
Thanks again, merged.

**Pull request merged**
